In [ ]:
!pip install rdkit
from rdkit import Chem




In [ ]:
mol = Chem.MolFromSmiles("CC(=O)Nc1ccc(O)cc1")

In [ ]:
node_features = []
for atom in mol.GetAtoms():
  node_f = []
  # atomic num
  node_f.append(atom.GetAtomicNum())
  # degree
  node_f.append(atom.GetDegree())
  # total degree
  node_f.append(atom.GetTotalDegree())
  # Total number of hydrogens
  node_f.append(atom.GetTotalNumHs())
  # formal charge
  node_f.append(atom.GetFormalCharge())
  # hibridization
  node_f.append(atom.GetHybridization())
  # Number of radical electrons
  node_f.append(atom.GetNumRadicalElectrons())
  # Aromaticity
  node_f.append(atom.GetIsAromatic())
  # mass
  node_f.append(atom.GetMass())
  # in ring
  node_f.append(atom.IsInRing())
  # Chirality
  node_f.append(atom.GetChiralTag())

  node_features.append(node_f)

node_features[0]

[6,
 1,
 4,
 3,
 0,
 rdkit.Chem.rdchem.HybridizationType.SP3,
 0,
 False,
 12.011,
 False,
 rdkit.Chem.rdchem.ChiralType.CHI_UNSPECIFIED]

In [ ]:
import numpy as np

node_features = np.asarray(node_features)

node_features[:, -2]

array([0., 0., 0., 0., 1., 1., 1., 1., 0., 1., 1.])

In [ ]:
edge_attributes = []
for bond in mol.GetBonds():
  edge_attributes.append([
    bond.GetBondTypeAsDouble(),
    bond.GetIsAromatic(),
    bond.IsInRing(),
    bond.GetIsConjugated(),
    int(bond.GetStereo())
]
  )

edge_attributes[0]

[1.0, False, False, False, 0]

In [ ]:
edges_attributes_np = np.asarray(edge_attributes)
edges_attributes_np[0]

array([1., 0., 0., 0., 0.])

In [ ]:
import torch

t = torch.tensor(edges_attributes_np, dtype=torch.float32)


In [ ]:
t.shape, t[0]

(torch.Size([11, 5]), tensor([1., 0., 0., 0., 0.]))

In [ ]:
x = []
y = [1,2]
x += [y, y]
x

[[1, 2], [1, 2]]

In [ ]:
src, dest = [], []
for bond in mol.GetBonds():
  i = bond.GetBeginAtomIdx()
  j = bond.GetEndAtomIdx()
  src += [i, j]
  dest += [j, i]

src, dest

([0, 1, 1, 2, 1, 3, 3, 4, 4, 5, 5, 6, 6, 7, 7, 8, 7, 9, 9, 10, 10, 4],
 [1, 0, 2, 1, 3, 1, 4, 3, 5, 4, 6, 5, 7, 6, 8, 7, 9, 7, 10, 9, 4, 10])

In [ ]:
torch.tensor([src, dest])

tensor([[ 0,  1,  1,  2,  1,  3,  3,  4,  4,  5,  5,  6,  6,  7,  7,  8,  7,  9,
          9, 10, 10,  4],
        [ 1,  0,  2,  1,  3,  1,  4,  3,  5,  4,  6,  5,  7,  6,  8,  7,  9,  7,
         10,  9,  4, 10]])

In [ ]:
import torch

lst = []
tensor = torch.tensor([[1, 2, 3], [1,1,1]])
lst.append(tensor)
lst.append(tensor)
x = sum(lst)
x

tensor([[2, 4, 6],
        [2, 2, 2]])

In [ ]:
t1 = torch.tensor([[1,2,3],[7,8,9]])
t2 = torch.tensor([[4,5,6],[10,11,12]])

res = torch.cat((t1, t2), dim=1)
res

tensor([[ 1,  2,  3,  4,  5,  6],
        [ 7,  8,  9, 10, 11, 12]])

In [ ]:
res1 = torch.cat((t1,t2), dim=0)
res1

tensor([[ 1,  2,  3],
        [ 7,  8,  9],
        [ 4,  5,  6],
        [10, 11, 12]])

In [3]:
from google.colab import drive
drive.mount('/content/drive')

import os
import sys
project_root = '/content/drive/MyDrive/GNNs/HIV inhibitors-GNN'
os.chdir(project_root)
sys.path.append(project_root)

Mounted at /content/drive


In [4]:
import torch
!pip install torch-geometric


     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 63.7/63.7 kB 4.4 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 1.3/1.3 MB 40.8 MB/s eta 0:00:00


In [7]:
!pip install rdkit
from torch_geometric.data import Dataset
from torch_geometric.loader import DataLoader
from src.dataset.dataset import MoleculeDataSet

root = "data"
train_dataset = MoleculeDataSet(root, filename="HIV_train_val.csv")
train_dataset

   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 36.7/36.7 MB 50.5 MB/s eta 0:00:00


Processing...


row path data/raw/HIV_train_val.csv


  2%|▏         | 658/37008 [08:21<7:42:11,  1.31it/s]


KeyboardInterrupt: 